---
AWSTemplateFormatVersion: "2010-09-09"

Description: >
    Mikias Hundie
    Udacity Project Deploy a High-Availability Web App using CloudFormation

Parameters:
  EnvironmentName:
    Description: Network Environment Name 
    Type: String
    